export enum ROOT_ROUTES {
  AUTH_NAVIGATION = 'AUTH_NAVIGATION',
  APP_NAVIGATION = 'APP_NAVIGATION',
}

export enum AUTH_NAVIGATION {
  LOGIN_SCREEN = '[AUTH] LOGIN_SCREEN',
  BASIC_INFORMATION = '[AUTH] BASIC_INFORMATION',
  ADDITIONAL_INFORMATION = '[AUTH] ADDITIONAL_INFORMATION',
  PURPOSE = '[AUTH] PURPOSE',
  SUCCESS = '[AUTH] SUCCESS',
}

export enum APP_NAVIGATION {
  HOME = '[APP] HOME',
  SEARCH = '[APP] SEARCH',
  CREATE = '[APP] CREATE',
  NOTIFICATION = '[APP] NOTIFICATION',
  PROFILE = '[APP] PROFILE',
  COMMENT = '[APP] COMMENT',
  CHAT = '[APP] CHAT',
  MEDIA = '[APP] MEDIA',
}

export enum HOME_NAVIGATION {
  NEW_FEED = '[HOME] NEW_FEED',
}
